version: '3'

networks:
  application_network:
    ipam:
      config:
        - subnet: 174.20.0.0/24

services:

  datasupplier:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
    networks:
      - application_network

  kafdrop:
    image: obsidiandynamics/kafdrop:3.31.0
    restart: no
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka:29092
      - JVM_OPTS=-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify
      - CMD_ARGS=--message.format=PROTOBUF --protobufdesc.directory=/descriptors
    depends_on:
      - kafka
    networks:
      - application_network
    volumes: 
      - ./descriptors:/descriptors

  kafka:
    image: obsidiandynamics/kafka
    restart: no
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      # - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://10.241.201.234:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_SESSION_TIMEOUT=6000
      - KAFKA_RESTART_ATTEMPTS=10
      - KAFKA_RESTART_DELAY=5
      - ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL=0
    networks:
      - application_network